version: "3"
services:
  backend:
    image: backend
    depends_on:
      - db
    build:
      context: ./backend
    environment:
      - DB_URL=postgresql+psycopg2://postgres:postgres@db:5432/library
      - PYTHONUNBUFFERED=0
    ports:
      - "8000:8000"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
